config/routes.rb
Rails.application.routes.draw do
  get 'applicants/index'
  get 'applicants/new'
  resources :companies, only: [:new, :edit, :update, :create]
  resources :positions
  resources :applicants, only: [:index, :new, :create]
  devise_for :users
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  belongs_to :user
  belongs_to :position
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :positions
  has_one_attached :logo
  validates :name, :url, presence: true
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :company

  enum career: [:developer, :business_inteligence, :information_technology, :design, :product, :technology, :other]
  enum contract: [:clt, :pj, :match]

  validates :name, :career, :contract, :city, :state, :summary, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :company
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company = current_user.build_company
  end

  def edit
    @company = current_user.company
  end

  def create
    @company = current_user.build_company(company_params)
    if @company.save
      flash[:notice] = 'Empresa cadastrada com sucesso.'
      redirect_to root_path
    else
      flash[:error] = 'Erro ao cadastrar a empresa.'
      render :new
    end
  end

  def update
  end

  private

  def company_params
    params.require(:company).permit(:name, :url, :logo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_company, :set_i18n_careers, :set_i18n_contracts
  before_action :set_position, only: [:edit, :show, :update]

  def index
    @positions = @company.positions
  end

  def new
    @position = @company.positions.new
  end

  def edit
  end

  def show
  end

  def create
    @position = @company.positions.new(params_position)
    if @position.save
      flash[:success] = 'Vaga cadastrada com sucesso.'
      redirect_to positions_path
    else
      render :new
    end
  end

  def update
    if @position.update(params_position)
      redirect_to positions_path
    else
      render :edit
    end
  end

  private

  def set_position
    @position = @company.positions.find(params[:id])
  end

  def params_position
    params.require(:position).permit(:name, :career, :contract, :remote, :publish, :city, :state, :summary, :description)
  end

  def set_company
    redirect_to new_company_path if current_user.company.nil?
    @company = current_user.company
  end

  def set_i18n_careers
    @careers = I18n.t('activerecord.attributes.position.careers')
    # @careers = []
    # Position.careers.each_with_index do |career, index|
    #   @careers << [
    #     Position.careers.to_a[index].first,
    #     I18n.t('activerecord.attributes.position.careers').values.to_a[index]
    #   ]
    # end
  end

  def set_i18n_contracts
    @contracts = I18n.t('activerecord.attributes.position.contracts')
    # @contracts = []
    # Position.contracts.each_with_index do |career, index|
    #   @contracts << [
    #     Position.contracts.to_a[index].first,
    #     I18n.t('activerecord.attributes.position.contracts').values.to_a[index]
    #   ]
    # end
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def dynamic_url_company
    if current_user.company.present? && current_user.company.try(:id).present?
      edit_company_path(current_user.company)
    else
      new_company_path
    end
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/applicants/index.html.haml
%h1 Applicants#index
%p Find me in app/views/applicants/index.html.haml

app/views/applicants/new.html.haml
%h1 Applicants#new
%p Find me in app/views/applicants/new.html.haml

app/views/companies/_form.html.haml
= simple_form_for @company do |f|
  = f.input :name
  = f.input :url
  = image_tag(url_for(@company.logo), class: 'company-logo') unless @company.new_record? && !@company.logo.nil?
  = f.input :logo
  = f.button :submit, class: 'btn btn-primary'

app/views/companies/edit.html.haml
%h2 Minha Empresa
= render 'form'

app/views/companies/new.html.haml
%h2 Minha Empresa
= render 'form'

app/views/home/index.html.haml
= render "shared/topbar"
-# %br
-# = image_pack_tag("media/images/test.jpg")

/ Button trigger modal
-# %button.btn.btn-primary{"data-bs-target" => "#exampleModal", "data-bs-toggle" => "modal", :type => "button"}
-#   Launch demo modal
-# / Modal
-# #exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :tabindex => "-1"}
-#   .modal-dialog
-#     .modal-content
-#       .modal-header
-#         %h5#exampleModalLabel.modal-title Modal title
-#         %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
-#       .modal-body
-#         \...
-#       .modal-footer
-#         %button.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Close
-#         %button.btn.btn-primary{:type => "button"} Save changes

.d-flex.align-items-center.p-3.my-3.text-white.bg-purple.rounded.shadow-sm
  -# %img.me-3{:alt => "", :height => "38", :src => "media/images/test.jpg", :width => "48"}/
  .lh-1
    %h1.h6.mb-0.text-white.lh-1 Bootstrap
    %small Since 2011
.my-3.p-3.bg-body.rounded.shadow-sm
  %h6.border-bottom.pb-2.mb-0 Recent updates
  .d-flex.text-muted.pt-3
    %svg.bd-placeholder-img.flex-shrink-0.me-2.rounded{"aria-label" => "Placeholder: 32x32", :focusable => "false", :height => "32", :preserveaspectratio => "xMidYMid slice", :role => "img", :width => "32", :xmlns => "http://www.w3.org/2000/svg"}
      %title Placeholder
      %rect{:fill => "#007bff", :height => "100%", :width => "100%"}
      %text{:dy => ".3em", :fill => "#007bff", :x => "50%", :y => "50%"} 32x32
    %p.pb-3.mb-0.small.lh-sm.border-bottom
      %strong.d-block.text-gray-dark @username
      Some representative placeholder content, with some information about this user. Imagine this being some sort of status update, perhaps?
  .d-flex.text-muted.pt-3
    %svg.bd-placeholder-img.flex-shrink-0.me-2.rounded{"aria-label" => "Placeholder: 32x32", :focusable => "false", :height => "32", :preserveaspectratio => "xMidYMid slice", :role => "img", :width => "32", :xmlns => "http://www.w3.org/2000/svg"}
      %title Placeholder
      %rect{:fill => "#e83e8c", :height => "100%", :width => "100%"}
      %text{:dy => ".3em", :fill => "#e83e8c", :x => "50%", :y => "50%"} 32x32
    %p.pb-3.mb-0.small.lh-sm.border-bottom
      %strong.d-block.text-gray-dark @username
      Some more representative placeholder content, related to this other user. Another status update, perhaps.
  .d-flex.text-muted.pt-3
    %svg.bd-placeholder-img.flex-shrink-0.me-2.rounded{"aria-label" => "Placeholder: 32x32", :focusable => "false", :height => "32", :preserveaspectratio => "xMidYMid slice", :role => "img", :width => "32", :xmlns => "http://www.w3.org/2000/svg"}
      %title Placeholder
      %rect{:fill => "#6f42c1", :height => "100%", :width => "100%"}
      %text{:dy => ".3em", :fill => "#6f42c1", :x => "50%", :y => "50%"} 32x32
    %p.pb-3.mb-0.small.lh-sm.border-bottom
      %strong.d-block.text-gray-dark @username
      This user also gets some representative placeholder content. Maybe they did something interesting, and you really want to highlight this in the recent updates.
  %small.d-block.text-end.mt-3
    %a{:href => "#"} All updates
.my-3.p-3.bg-body.rounded.shadow-sm
  %h6.border-bottom.pb-2.mb-0 Suggestions
  .d-flex.text-muted.pt-3
    %svg.bd-placeholder-img.flex-shrink-0.me-2.rounded{"aria-label" => "Placeholder: 32x32", :focusable => "false", :height => "32", :preserveaspectratio => "xMidYMid slice", :role => "img", :width => "32", :xmlns => "http://www.w3.org/2000/svg"}
      %title Placeholder
      %rect{:fill => "#007bff", :height => "100%", :width => "100%"}
      %text{:dy => ".3em", :fill => "#007bff", :x => "50%", :y => "50%"} 32x32
    .pb-3.mb-0.small.lh-sm.border-bottom.w-100
      .d-flex.justify-content-between
        %strong.text-gray-dark Full Name
        %a{:href => "#"} Follow
      %span.d-block @username
  .d-flex.text-muted.pt-3
    %svg.bd-placeholder-img.flex-shrink-0.me-2.rounded{"aria-label" => "Placeholder: 32x32", :focusable => "false", :height => "32", :preserveaspectratio => "xMidYMid slice", :role => "img", :width => "32", :xmlns => "http://www.w3.org/2000/svg"}
      %title Placeholder
      %rect{:fill => "#007bff", :height => "100%", :width => "100%"}
      %text{:dy => ".3em", :fill => "#007bff", :x => "50%", :y => "50%"} 32x32
    .pb-3.mb-0.small.lh-sm.border-bottom.w-100
      .d-flex.justify-content-between
        %strong.text-gray-dark Full Name
        %a{:href => "#"} Follow
      %span.d-block @username
  .d-flex.text-muted.pt-3
    %svg.bd-placeholder-img.flex-shrink-0.me-2.rounded{"aria-label" => "Placeholder: 32x32", :focusable => "false", :height => "32", :preserveaspectratio => "xMidYMid slice", :role => "img", :width => "32", :xmlns => "http://www.w3.org/2000/svg"}
      %title Placeholder
      %rect{:fill => "#007bff", :height => "100%", :width => "100%"}
      %text{:dy => ".3em", :fill => "#007bff", :x => "50%", :y => "50%"} 32x32
    .pb-3.mb-0.small.lh-sm.border-bottom.w-100
      .d-flex.justify-content-between
        %strong.text-gray-dark Full Name
        %a{:href => "#"} Follow
      %span.d-block @username
  %small.d-block.text-end.mt-3
    %a{:href => "#"} All suggestions

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title OpenVagas
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/topbar'
    %main.container{:role => "main"}
      = yield
    %footer
      %p Sistema desenvolvido pro Elton Santos
      %p= "Desde de #{Time.new.year}"

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title OpenVagas
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #logreg-forms
      = yield

app/views/positions/_form.html.haml
= simple_form_for @position do |f|
  = f.input :name
  = f.input :career, as: :select, collection: @careers, label_method: :second, value_method: :first, include_blank: false, selected: @position.career
  = f.input :contract, as: :select, collection: @contracts, label_method: :second, value_method: :first, include_blank: false, selected: @position.contract
  = f.input :remote
  = f.input :publish
  = f.input :city
  = f.input :state
  = f.input :summary
  = f.input :description
  = f.button :submit, class: 'btn btn-primary'

app/views/positions/edit.html.haml
%h2 Editar vaga
= render 'form'

app/views/positions/index.html.haml
%h2 Minhas vagas

%table.table
  %thead.thead-dark
    %tr
      %th{:scope => "col"} Título
      %th{:scope => "col"} Carreira
      %th{:scope => "col"} Local
      %th{:scope => "col"} Tipo de contrato
      %th{:scope => "col"} Candidaturas
      %th{:scope => "col"} Ações
  %tbody
    - @positions.each do |position|
      %tr
        %th{:scope => "row"}= position.name
        %td= position.career
        %td= position.remote # aplicar helper
        %td= position.contract
        %td 1 (ver detalhes)
        %td
          = link_to 'Editar', edit_position_path(position)

app/views/positions/new.html.haml
%h2 Publica vaga
= render 'form'

app/views/positions/show.html.haml
%h1 Positions#show
%p Find me in app/views/positions/show.html.haml

app/views/shared/_topbar.html.haml
%nav.navbar.navbar-expand-md.fixed-top.navbar-dark.bg-dark
  %a.navbar-brand{:href => "#"} Open Vagas
  %button.navbar-toggler.p-0.border-0{"data-toggle" => "offcanvas", :type => "button"}
    %span.navbar-toggler-icon
  #navbarsExampleDefault.navbar-collapse.offcanvas-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => root_path}
          Inicio
          %span.sr-only (current)
      - unless user_signed_in?
        %li.nav-item
          = link_to 'Login/Cadastro', new_user_session_path, class: 'nav-link'
      - if user_signed_in?
        %li.nav-item.active
          %a.nav-link{:href => dynamic_url_company}
            Minha Empresa
        %li.nav-item.dropdown
          %a#dropdown01.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#"} Settings
          .dropdown-menu{"aria-labelledby" => "dropdown01"}
            = link_to('Sair', destroy_user_session_path, method: :delete, class: 'dropdown-item')
        %li.nav-item
          %a.nav-link.public-position{:href => new_position_path}
            Publicar vaga